### ISSUE TITLE
[Feature] Add the ability to activate validations for Properties depending of the state of another property

### ISSUE THREAD

**Issue by lennykey** [konform-kt/konform#20] opened 2020-04-20 09:28 UTC
Example:

if a firstName was passed to a Person and this firstName is present then the user should also enter a familyName to pass the validation
if the firstName was not passed (null) then the validation for the familyName should not be active
Something like this should be possible:

```
data class Person(val name: String?, val familyName: String?)


 val validator = Validation<Person> {
        Person::name ifPresent {
            minLength(1)

            Person::familyName {
                minLength(1)
            }
        }

        Person::familyName ifPresent {
            minLength(1)

            Person::name {
                minLength(1)
            }

        }
    }
```

**Comment by sebdak** [comment] 2021-03-10 08:43
On a similar note to this, is it possible to somehow infer that a nullable property is non-null if declared as `required` in the validation spec?

```kotlin
data class UserProfile(
        val fullName: String,
        val age: Int?
)

val validateUser = Validation<UserProfile> {
    UserProfile::fullName {
        minLength(2)
        maxLength(100)
    }

    UserProfile::age required {
        minimum(0)
        maximum(150)
    }
}

val user = UserProfile("username", 1)
val validationResult = validateUser.validate(user)

when (validationResult) {
    is Valid -> {
        // validationResult.value.age is inferred to type "Int" instead of "Int?"
    }
}
```

**Comment by dhoepelman** [comment] 2024-05-10 16:20
Duplicate of #29

**Closed by dhoepelman** 2024-05-10 16:20 UTC
Labels: enhancement
