### ISSUE TITLE
Custom types for hints / error messages

### ISSUE THREAD

**Issue by Bendzae** [konform-kt/konform#146] opened 2024-10-16 13:18 UTC
## Context
Currently a hint or errorMessage has to be a string. It would be great to be able to supply a custom type for these to allow a more flexibility in the we different applications might model their errors. 

## Proposed solution
- Introduce a new type parameter to the `Validation` class: `Validation<T,E>` where `E` is the type of the error format.
- Allow passing this type as a hint/errorMessage. Example:
```kotlin
enum class CustomError(description: String, severity: Severity) {
    SOME_ERROR("This is some error", Severity.HIGH),
    SOME_OTHER_ERROR("This is some other error", Severity.MEDIUM),
}
Validation<MyClass, CustomError> {
    MyClass::someValue {
        min(0) hint CustomError.SOME_ERROR
    }
}
```

Of course library default messages like "is required" would need to be customisable then (which would be a great feature anyways).

I would be more then happy to create a PR to implement this if it is something that could be considered 🙂

**Comment by dhoepelman** [comment] 2024-10-16 15:11
Thanks for the proposal. Currently not interested in doing this for mainly 2 reasons:

* It's a large breaking change to the API, would require much existing code to be rewritten
    * The alternative would be to add a second type, but this would bloat the API a lot
* The primary purpose of this library is to validate with human-readable, not to handle different validation scenarios separately.

You can take a look at [Arrow's Either for validation](https://arrow-kt.io/learn/typed-errors/validation/), which has the customizable arrow type.

For the specific example given I would personally probably make a `Validation` per severity level, and then collect them using the `ValidationResult.errors` list

**Comment by Bendzae** [comment] 2024-10-16 17:52
Alright that makes a lot of sense. Thank you for the quick reply and great work on konform anyways!

**Comment by dhoepelman** [comment] 2024-11-10 13:08
Reopening this, thinking of supporting this with the following API:

It's not typesafe at the `Validation` level, but it does support this functionality, and I except it to be fairly niche so good enough. I don't think adding a new generic type can be done in a backwards compatible way so this'll have to do

```kotlin
constraint(
  hint = "...",
  userContext = CustomError.SOME_ERROR
) {
  // ...
}

val invalid = validation(data) as? Invalid
val errors1 = invalid?.errors.filter { it.userContext == CustomError.SOME_ERROR }
val errors2 = invalid?.errors.filter { it.userContext == CustomsError.SOME_OTHER_ERROR } 
```

**Comment by dhoepelman** [comment] 2024-11-13 08:57
Duplicate of #48

**Closed by dhoepelman** 2024-11-13 08:57 UTC
